--- 
abstract: Helps you determine best size for your Tk-Wizard application
author: 
  - Martin 'Kingpin' Thurn <mthurn@cpan.org>
build_requires: 
  Data::Dumper: 0
  ExtUtils::testlib: 0
  IO::Capture::Stdout::Extended: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Tk: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Tk-Wizard-Sizer
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Tk::Wizard: 0
version: 2.224
